<a href="https://colab.research.google.com/github/debg48/pytorch_for_beginners/blob/main/DataloaderPyTorchipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dataset and DataLoader

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np
import math

In [6]:
class WineDataset(Dataset):

  def __init__(self):
    xy = np.loadtxt('/content/wine.csv',delimiter=",",dtype=np.float32,skiprows=1)
    self.n_samples = xy.shape[0]
    self.x_data = torch.from_numpy(xy[:,1:])
    self.y_data =torch.from_numpy(xy[:,[0]])

  def __getitem__(self,index):
    return self.x_data[index],self.y_data[index]

  def __len__(self):
    return self.n_samples

In [7]:
dataset = WineDataset()

Test the if everything is ok

In [8]:
first_data = dataset[0]
features,labels = first_data
features,labels

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03]),
 tensor([1.]))

use Dataloader to create batches of data

In [9]:
dataloader = DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=2)

Let us take a look at the reults

In [10]:
dataiter=iter(dataloader)
data=next(dataiter)
features,labels=data
features,labels

(tensor([[1.3400e+01, 3.9100e+00, 2.4800e+00, 2.3000e+01, 1.0200e+02, 1.8000e+00,
          7.5000e-01, 4.3000e-01, 1.4100e+00, 7.3000e+00, 7.0000e-01, 1.5600e+00,
          7.5000e+02],
         [1.2000e+01, 1.5100e+00, 2.4200e+00, 2.2000e+01, 8.6000e+01, 1.4500e+00,
          1.2500e+00, 5.0000e-01, 1.6300e+00, 3.6000e+00, 1.0500e+00, 2.6500e+00,
          4.5000e+02],
         [1.3480e+01, 1.8100e+00, 2.4100e+00, 2.0500e+01, 1.0000e+02, 2.7000e+00,
          2.9800e+00, 2.6000e-01, 1.8600e+00, 5.1000e+00, 1.0400e+00, 3.4700e+00,
          9.2000e+02],
         [1.1960e+01, 1.0900e+00, 2.3000e+00, 2.1000e+01, 1.0100e+02, 3.3800e+00,
          2.1400e+00, 1.3000e-01, 1.6500e+00, 3.2100e+00, 9.9000e-01, 3.1300e+00,
          8.8600e+02]]),
 tensor([[3.],
         [2.],
         [1.],
         [2.]]))

Let us create a dummy training loop to get a better idea of how things work

In [22]:
num_epochs = 2
total_samples = len(dataset)
n_iters = math.ceil(total_samples/4) # batch_size = 4 change accordingly
print(total_samples,n_iters)
for epoch in range(num_epochs):
  for i ,(inputs,labels) in enumerate(dataloader):
    if (i+1)%5==0:
      print(f'Epoch : {epoch+1}/{num_epochs}, Step : {i+1}/{n_iters} | Input : {inputs.shape} | Output : {labels.shape}')

178 45
Epoch : 1/2, Step : 5/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 10/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 15/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 20/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 25/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 30/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 35/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 40/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 1/2, Step : 45/45 | Input : torch.Size([2, 13]) | Output : torch.Size([2, 1])
Epoch : 2/2, Step : 5/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 2/2, Step : 10/45 | Input : torch.Size([4, 13]) | Output : torch.Size([4, 1])
Epoch : 2/2, Step : 15/45 | Input : torch.Size([4

We can also use built-in datasets from torchvison library

In [16]:
train_dataset = torchvision.datasets.MNIST(root='./data',train=True,transform=torchvision.transforms.ToTensor(),download=True)

100%|██████████| 9912422/9912422 [00:00<00:00, 83308709.33it/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 33124335.20it/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 20913644.88it/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 15551452.06it/s]


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw



In [17]:
train_loader = DataLoader(dataset=train_dataset,
                                           batch_size=3,
                                           shuffle=True)

In [ ]:
num_epochs = 2
total_samples = len(train_dataset)
n_iters = math.ceil(total_samples/3) # batch_size = 3 change accordingly
print(total_samples,n_iters)
for epoch in range(num_epochs):
  for i ,(inputs,labels) in enumerate(train_loader):
    if (i+1)%5==0:
      print(f'Epoch : {epoch+1}/{num_epochs}, Step : {i+1}/{n_iters} | Input : {inputs.shape} | Output : {labels.shape}')

#Dataset Transforms

We modify our WineDataset class

In [23]:
class WineDataset(Dataset):

  def __init__(self,transform=None):
    xy = np.loadtxt('/content/wine.csv',delimiter=",",dtype=np.float32,skiprows=1)
    self.n_samples = xy.shape[0]
    self.x_data = xy[:,1:]
    self.y_data = xy[:,[0]]
    self.transform = transform

  def __getitem__(self,index):
    sample = self.x_data[index],self.y_data[index]
    if self.transform :
      sample = self.transform(sample)
    return sample

  def __len__(self):
    return self.n_samples

Let us create our own custom transform for converting numpy array to tensors

In [24]:
class ToTensor:
  def __call__(self,sample):
    inputs,targets=sample
    return torch.from_numpy(inputs),torch.from_numpy(targets)

In [26]:
print("Without Transform : ")
dataset = WineDataset()
first_data = dataset[0]
features,labels = first_data
print(type(features),type(labels))
print(features,labels)

print("\nWith Tensor : ")
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
features,labels = first_data
print(type(features),type(labels))
print(features,labels)

Without Transform : 
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03] [1.]

With Tensor : 
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [29]:
class MulTransform:

  def __init__(self,factor):
    self.factor = factor

  def __call__(self,sample):
    inputs,targets = sample
    inputs *= self.factor
    return inputs,targets

In [30]:
print("With multiple transform : ")
composed = torchvision.transforms.Compose([ToTensor(),MulTransform(3)])
dataset = WineDataset(transform=composed)
first_data = dataset[0]
features,labels = first_data
print(type(features),type(labels))
print(features,labels)

With multiple transform : 
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([4.2690e+01, 5.1300e+00, 7.2900e+00, 4.6800e+01, 3.8100e+02, 8.4000e+00,
        9.1800e+00, 8.4000e-01, 6.8700e+00, 1.6920e+01, 3.1200e+00, 1.1760e+01,
        3.1950e+03]) tensor([1.])
