<a href="https://colab.research.google.com/github/debg48/pytorch_for_beginners/blob/main/SamplingFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  PyTorch Functions for Sampling


### PyTorch

PyTorch is an open source deep learning framework built to be flexible and modular for research, with the stability and support needed for production deployment. PyTorch provides a Python package for high-level features like tensor computation (like NumPy) with strong GPU acceleration and TorchScript for an easy transition between eager mode and graph mode. With the latest release of PyTorch, the framework provides graph-based execution, distributed training, mobile deployment, and quantization.

### Random Sampling

Random sampling is a part of the sampling technique in which each sample has an equal probability of being chosen. A sample chosen randomly is meant to be an unbiased representation of the total population. If for some reasons, the sample does not represent the population, the variation is called a sampling error.

Random sampling is one of the simplest forms of collecting data from the total population. Under random sampling, each member of the subset carries an equal opportunity of being chosen as a part of the sampling process. For example, the total workforce in organisations is 300 and to conduct a survey, a sample group of 30 employees is selected to do the survey. In this case, the population is the total number of employees in the company and the sample group of 30 employees is the sample. Each member of the workforce has an equal opportunity of being chosen because all the employees which were chosen to be part of the survey were selected randomly. But, there is always a possibility that the group or the sample does not represent the population as a whole, in that case, any random variation is termed as a sampling error.

An unbiased random sample is important for drawing conclusions. For example when we took out the sample of 30 employees from the total population of 300 employees, there is always a possibility that a researcher might end up picking over 25 men even if the population consists of 200 men and 100 women. Hence, some variations when drawing results can come up, which is known as a sampling error. One of the disadvantages of random sampling is the fact that it requires a complete list of population. For example, if a company wants to carry out a survey and intends to deploy random sampling, in that case, there should be total number of employees and there is a possibility that all the employees are spread across different regions which make the process of survey little difficult.

- torch.bernoulli()
- torch.Tensor.cauchy_()
- torch.poisson()
- torch.normal()
- torch.rand()

Before we begin, let's install and import PyTorch

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.bernoulli()

torch.bernoulli() method is used to draw binary random numbers (0 or 1) from a Bernoulli distribution. This method accepts a tensor as a parameter, and this input tensor is the probability of drawing 1. The values of the input tensor should be in the range of 0 to 1. This method returns a tensor that only has values 0 or 1 and the size of this tensor is the same as the input tensor


In [ ]:
a = torch.empty(3, 3).uniform_(0, 1)
a

tensor([[0.0966, 0.7385, 0.6546],
        [0.4255, 0.8294, 0.8315],
        [0.8065, 0.8228, 0.6467]])

In [ ]:
# Example 1 - working 
torch.bernoulli(a)

tensor([[0., 1., 1.],
        [1., 1., 0.],
        [1., 0., 1.]])

The input was a tensor containing probabilities of drawing 1 and hence the function returns corresponding tensor 

In [ ]:
a = torch.ones(3, 3) 
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Example 2 - working
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

As the probabilities were one the function returns a tensor with all elements as 1 

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a=torch.tensor([[-1, 2,5], [3, 4, 5]])
a

tensor([[-1,  2,  5],
        [ 3,  4,  5]])

In [ ]:
torch.bernoulli(a)

RuntimeError: "bernoulli_tensor_cpu_p_" not implemented for 'Long'

Probability canot be nagative hence the function fails to return a tensor


The Bernoulli distribution is a discrete distribution having two possible outcomes labelled by and in which (“success”) occurs with probability and (“failure”) occurs with probability , where . It therefore has probability density function.

## Function 2 - torch.Tensor.cauchy_()

Fills the tensor with numbers drawn from the Cauchy distribution

In [ ]:
a = torch.empty(3, 3)
a

tensor([[-2.2242e-38,  3.0746e-41, -2.3631e-38],
        [ 3.0746e-41,  1.5695e-43,  0.0000e+00],
        [ 6.7262e-44,  0.0000e+00, -2.3912e-38]])

In [ ]:
torch.Tensor.cauchy_(a)

tensor([[ -0.3098,  -0.7789,  -1.4854],
        [-41.7906,   0.3488,   0.8408],
        [ -2.7455,   1.3863,  -0.9825]])

The vector with uninitialized data is filled with numbers from a cauchy distribution

In [ ]:
# Example 2 - workinga = torch.ones(3, 3) 
a = torch.ones(3, 3) 
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.Tensor.cauchy_(a)

tensor([[-4.5374,  0.3726,  0.4947],
        [ 0.4111,  0.9167,  0.7214],
        [ 1.0533, -9.2247,  0.7620]])

The vector is filled with numbers from a cauchy distribution

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.ones(4, 4, dtype = torch.int32)
a

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [ ]:
torch.Tensor.cauchy_(a)

RuntimeError: "cauchy_cpu" not implemented for 'Int'

The input tensor must be floating point datatype

The Cauchy distribution, sometimes called the Lorentz distribution, is a family of continuous probably distributions which resemble the normal distribution family of curves. While the resemblance is there, it has a taller peak than a normal. And unlike the normal distribution, it’s fat tails decay much more slowly.

The Cauchy distribution is well known for the fact that it’s expected value and other moments do not exist. The median and mode do exist. And for the Cauchy, they are equal. Together, they tell you where the line of symmetry is. However, the Central Limit theorem doesn’t work for the limiting distribution of the mean. In sum, this distribution behaves so abnormally it’s sometimes considered the Hannibal Lecter of distributions.


## Function 3 - torch.poisson()

Returns a tensor of the same size as input with each element sampled from a Poisson distribution with rate parameter given by the corresponding element in input

In [ ]:
# Example 1 - working (from official documentation)
a= torch.rand(4, 4) * 5  # rate parameter between 0 and 5
torch.poisson(a) 

tensor([[2., 1., 0., 8.],
        [2., 3., 3., 3.],
        [0., 0., 1., 6.],
        [0., 5., 3., 3.]])

Returns a output from a poisson distribution for input tensor containing rate parameter between 0 and 5

In [ ]:
# Example 2 - working
a= torch.rand(4, 4) * 9  # rate parameter between 0 and 9
torch.poisson(a) 

tensor([[10.,  7.,  4.,  3.],
        [ 2.,  2.,  7.,  6.],
        [ 4.,  0., 10.,  3.],
        [ 6.,  1.,  4.,  5.]])

Returns a output from a poisson distribution for input tensor containing rate parameter between 0 and 9

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.ones(3,3, dtype = torch.int32)
torch.poisson(a)

RuntimeError: "poisson_cpu" not implemented for 'Int'

The input tensor must be floating point datatype

In Statistics, Poisson distribution is one of the important topics. It is used for calculating the possibilities for an event with the average rate of value. Poisson distribution is a discrete probability distribution.

## Function 4 - torch.normal()

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

The mean is a tensor with the mean of each output element’s normal distribution

The std is a tensor with the standard deviation of each output element’s normal distribution

The shapes of mean and std don’t need to match, but the total number of elements in each tensor need to be the same.

In [ ]:
# Example 1 - working
torch.normal(mean=torch.arange(1., 6.))

tensor([1.1424, 1.3351, 3.1882, 3.7897, 3.7148])

It returns a tensor of random numbers drawn from separate normal distributions whose standard deviation is 1.

In [ ]:
# Example 2 - working
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([-0.6932,  2.3833,  2.3547,  3.8103,  5.4436,  5.8295,  7.5898,  8.4793,
         9.1938, 10.0637])

It returns a tensor of random numbers drawn from separate normal distributions

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean= torch.ones(3,3), std= torch.ones(4,3))

RuntimeError: inconsistent tensor, std and mean are not broadcastable and have different number of elements, expected mean [3, 3] and std [4, 3] to have same number of elements)

The number of elements of mean and standard deviation needs to be same

Normal distribution, also known as the Gaussian distribution, is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.

In graphical form, the normal distribution appears as a "bell curve".

## Function 5 - torch.rand()

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)

The shape of the tensor is defined by the variable argument size.

In [ ]:
# Example 1 - working
torch.randn(4)

tensor([-0.7498,  1.0187, -1.9089, -0.1189])

The function returns random numbers from standard normal distribution for a given input.

In [ ]:
# Example 2 - working
torch.randn(4,4)

tensor([[-1.3119, -0.2177, -0.2496,  0.2361],
        [-1.2755, -0.2271,  1.5297,  0.6433],
        [-0.4198, -0.9269, -0.6260, -0.9713],
        [ 0.6730, -1.2400,  2.1338,  0.2051]])

The function returns random numbers from standard normal distribution.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randn(4, 5, dtype = torch.int32)

RuntimeError: "normal_kernel_cpu" not implemented for 'Int'

The input tensor must be floating point datatype

PyTorch torch.randn() returns a tensor defined by the variable argument size (sequence of integers defining the shape of the output tensor), containing random numbers from standard normal distribution.

The standard normal distribution, also called the z-distribution, is a special normal distribution where the mean is 0 and the standard deviation is 1

## Conclusion

Data is the currency of applied machine learning. Therefore, it is important that it is both collected and used effectively.

Data sampling refers to statistical methods for selecting observations from the domain with the objective of estimating a population parameter. Whereas data resampling refers to methods for economically using a collected dataset to improve the estimate of the population parameter and help to quantify the uncertainty of the estimate.

Both data sampling and data resampling are methods that are required in a predictive modeling problem.

In this notebook we went through five PyTorch functions for sampling.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* Jonathan Hui blog: https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/